import type {
  BodyZone,
  CapabilityDimension,
  CapabilityLevel,
  EquipmentType,
  Exercise,
  ExerciseMedia,
  ExerciseVariant,
  MovementPattern,
} from "@/lib/sport/types";

function media(exerciseId: string, altText: string): ExerciseMedia[] {
  return [
    {
      id: `${exerciseId}-media-placeholder`,
      exerciseId,
      kind: "illustration",
      placeholder: true,
      altText,
      source: "Emplacement reserve, aucun media externe importe.",
      license: "A fournir avant publication du media.",
      validationStatus: "draft_unreviewed",
    },
  ];
}

function variant(
  exerciseId: string,
  id: string,
  name: string,
  difficulty: CapabilityLevel,
  requiredEquipment: EquipmentType[],
  guidance: string,
  primaryCue: string,
  effortSecondsMin: number,
  effortSecondsMax: number,
  easierVariantId: string | null,
  harderVariantId: string | null,
): ExerciseVariant {
  return {
    id,
    exerciseId,
    name,
    difficulty,
    requiredEquipment,
    guidance,
    primaryCue,
    effortSecondsMin,
    effortSecondsMax,
    easierVariantId,
    harderVariantId,
  };
}

function exercise(args: {
  id: string;
  name: string;
  movementPattern: MovementPattern;
  capabilityDimension: CapabilityDimension;
  shortDescription: string;
  primaryCue: string;
  teachingSteps: string[];
  commonMistakes: string[];
  breathing: string;
  requiredEquipment: EquipmentType[];
  targetZones: BodyZone[];
  cautionZones: BodyZone[];
  difficulty: CapabilityLevel;
  effortSecondsMin: number;
  effortSecondsMax: number;
  variants: ExerciseVariant[];
  mediaAlt: string;
}): Exercise {
  return {
    id: args.id,
    name: args.name,
    activity: "strength",
    movementPattern: args.movementPattern,
    capabilityDimension: args.capabilityDimension,
    shortDescription: args.shortDescription,
    primaryCue: args.primaryCue,
    teachingSteps: args.teachingSteps,
    commonMistakes: args.commonMistakes,
    breathing: args.breathing,
    requiredEquipment: args.requiredEquipment,
    targetZones: args.targetZones,
    cautionZones: args.cautionZones,
    difficulty: args.difficulty,
    effortSecondsMin: args.effortSecondsMin,
    effortSecondsMax: args.effortSecondsMax,
    active: true,
    validationStatus: "draft_unreviewed",
    variants: args.variants,
    media: media(args.id, args.mediaAlt),
  };
}

export const STRENGTH_EXERCISES: Exercise[] = [
  exercise({
    id: "warmup_march",
    name: "Marche active sur place",
    movementPattern: "mobility",
    capabilityDimension: "cardio_endurance",
    shortDescription: "Elever progressivement le rythme sans impact.",
    primaryCue: "Garde une respiration facile et les appuis souples.",
    teachingSteps: [
      "Tiens-toi droit.",
      "Monte les genoux sans chercher la hauteur maximale.",
      "Balance naturellement les bras.",
    ],
    commonMistakes: ["Bloquer la respiration", "Taper fortement les pieds"],
    breathing: "Respiration naturelle, capable de parler.",
    requiredEquipment: [],
    targetZones: ["hips", "ankles"],
    cautionZones: ["ankles", "knees"],
    difficulty: 0,
    effortSecondsMin: 20,
    effortSecondsMax: 60,
    variants: [
      variant(
        "warmup_march",
        "warmup_march_easy",
        "Marche lente sur place",
        0,
        [],
        "Reste sur un rythme tres confortable.",
        "Appuis silencieux.",
        20,
        45,
        null,
        "warmup_march_active",
      ),
      variant(
        "warmup_march",
        "warmup_march_active",
        "Marche active sur place",
        1,
        [],
        "Ajoute un leger mouvement des bras.",
        "Respiration controlee.",
        30,
        60,
        "warmup_march_easy",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une marche active sur place.",
  }),
  exercise({
    id: "mobility_shoulders",
    name: "Mobilite des epaules",
    movementPattern: "mobility",
    capabilityDimension: "mobility",
    shortDescription: "Mobiliser doucement les epaules avant les efforts.",
    primaryCue: "Reste dans une amplitude confortable.",
    teachingSteps: [
      "Relache la nuque.",
      "Dessine de petits cercles avec les epaules.",
      "Inverse le sens sans forcer.",
    ],
    commonMistakes: ["Monter les epaules vers les oreilles", "Chercher une amplitude douloureuse"],
    breathing: "Expire pendant les cercles vers l'arriere.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders"],
    difficulty: 0,
    effortSecondsMin: 20,
    effortSecondsMax: 45,
    variants: [
      variant(
        "mobility_shoulders",
        "mobility_shoulders_small",
        "Cercles d'epaules courts",
        0,
        [],
        "Fais des cercles courts, lents et confortables.",
        "Aucune douleur recherchee.",
        20,
        40,
        null,
        "mobility_shoulders_full",
      ),
      variant(
        "mobility_shoulders",
        "mobility_shoulders_full",
        "Mobilite epaules complete",
        1,
        [],
        "Augmente seulement si le mouvement reste fluide.",
        "Nuque longue.",
        25,
        45,
        "mobility_shoulders_small",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une mobilisation douce des epaules.",
  }),
  exercise({
    id: "bodyweight_squat",
    name: "Demi-squat controle",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Renforcer les jambes avec une amplitude prudente.",
    primaryCue: "Pousse le sol et garde les genoux dans l'axe.",
    teachingSteps: [
      "Place les pieds a largeur confortable.",
      "Descends peu profond, comme vers une chaise imaginaire.",
      "Remonte sans a-coup.",
    ],
    commonMistakes: ["Descendre trop bas trop vite", "Laisser les genoux rentrer"],
    breathing: "Inspire en descendant, expire en remontant.",
    requiredEquipment: [],
    targetZones: ["knees", "hips"],
    cautionZones: ["knees", "hips", "ankles"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 40,
    variants: [
      variant(
        "bodyweight_squat",
        "bodyweight_squat_partial",
        "Demi-squat tres court",
        0,
        [],
        "Amplitude courte, mains libres ou posees sur les hanches.",
        "Mouvement lent.",
        15,
        30,
        null,
        "bodyweight_squat_controlled",
      ),
      variant(
        "bodyweight_squat",
        "bodyweight_squat_controlled",
        "Demi-squat controle",
        1,
        [],
        "Descends un peu plus si tout reste confortable.",
        "Genoux dans l'axe.",
        20,
        40,
        "bodyweight_squat_partial",
        "bodyweight_squat_deeper",
      ),
      variant(
        "bodyweight_squat",
        "bodyweight_squat_deeper",
        "Squat poids du corps adapte",
        2,
        [],
        "Amplitude moderee, toujours sans douleur.",
        "Buste stable.",
        25,
        45,
        "bodyweight_squat_controlled",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un demi-squat controle.",
  }),
  exercise({
    id: "sit_to_stand",
    name: "Assis-debout depuis une chaise",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Travailler les jambes avec un repere stable.",
    primaryCue: "Leve-toi en poussant dans les pieds.",
    teachingSteps: [
      "Assieds-toi au bord d'une chaise stable.",
      "Penche legerement le buste.",
      "Leve-toi puis reviens t'asseoir avec controle.",
    ],
    commonMistakes: ["Se laisser tomber sur la chaise", "Utiliser l'elan"],
    breathing: "Expire en te levant.",
    requiredEquipment: ["stable_chair"],
    targetZones: ["knees", "hips"],
    cautionZones: ["knees", "hips"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "sit_to_stand",
        "sit_to_stand_with_support",
        "Assis-debout avec appui",
        0,
        ["stable_chair"],
        "Utilise les mains legerement si necessaire.",
        "Controle la descente.",
        15,
        35,
        null,
        "sit_to_stand_no_hands",
      ),
      variant(
        "sit_to_stand",
        "sit_to_stand_no_hands",
        "Assis-debout sans les mains",
        1,
        ["stable_chair"],
        "Mains libres, rythme calme.",
        "Pieds bien ancres.",
        20,
        45,
        "sit_to_stand_with_support",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un assis-debout depuis une chaise.",
  }),
  exercise({
    id: "push_up_family",
    name: "Pompes adaptees",
    movementPattern: "push",
    capabilityDimension: "upper_push",
    shortDescription: "Poussee du haut du corps avec variante ajustee.",
    primaryCue: "Garde le corps solide et pousse sans bloquer la respiration.",
    teachingSteps: [
      "Place les mains sous ou legerement devant les epaules.",
      "Descends dans une amplitude confortable.",
      "Repousse le support sans creuser le dos.",
    ],
    commonMistakes: ["Creuser le bas du dos", "Hausser les epaules", "Aller jusqu'a l'echec"],
    breathing: "Inspire en descendant, expire en poussant.",
    requiredEquipment: [],
    targetZones: ["shoulders", "wrists"],
    cautionZones: ["shoulders", "wrists", "back"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 45,
    variants: [
      variant(
        "push_up_family",
        "push_wall",
        "Pompes contre un mur",
        0,
        [],
        "Place-toi face a un mur, pieds recules.",
        "Pousse le mur calmement.",
        10,
        35,
        null,
        "push_knees",
      ),
      variant(
        "push_up_family",
        "push_incline",
        "Pompes inclinees",
        1,
        ["stable_chair"],
        "Mains sur une chaise stable ou un support fixe.",
        "Corps aligne.",
        15,
        40,
        "push_wall",
        "push_standard",
      ),
      variant(
        "push_up_family",
        "push_knees",
        "Pompes sur les genoux",
        2,
        [],
        "Genoux au sol, mains sous les epaules.",
        "Descente controlee.",
        15,
        45,
        "push_wall",
        "push_standard",
      ),
      variant(
        "push_up_family",
        "push_standard",
        "Pompes classiques",
        3,
        [],
        "Position planche, amplitude confortable.",
        "Ne cherche pas l'echec.",
        15,
        45,
        "push_knees",
        "push_feet_elevated",
      ),
      variant(
        "push_up_family",
        "push_feet_elevated",
        "Pompes pieds sureleves",
        4,
        [],
        "Pieds poses plus haut que les mains, seulement si la pompe classique reste facile.",
        "Garde le meme controle.",
        15,
        45,
        "push_standard",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une variante de pompe adaptee.",
  }),
  exercise({
    id: "hip_hinge",
    name: "Charniere de hanches",
    movementPattern: "hinge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Apprendre le mouvement de hanches sans charge.",
    primaryCue: "Recule les hanches en gardant le dos long.",
    teachingSteps: [
      "Pieds stables, genoux legerement souples.",
      "Recule les hanches comme pour toucher un mur.",
      "Reviens debout en serrant legerement les fessiers.",
    ],
    commonMistakes: ["Arrondir le dos", "Transformer le geste en squat"],
    breathing: "Inspire en reculant les hanches, expire en revenant.",
    requiredEquipment: [],
    targetZones: ["hips", "back"],
    cautionZones: ["back", "hips"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "hip_hinge",
        "hinge_wall_touch",
        "Charniere vers un mur",
        0,
        [],
        "Recule doucement les hanches vers un mur proche.",
        "Dos long.",
        15,
        35,
        null,
        "hinge_good_morning",
      ),
      variant(
        "hip_hinge",
        "hinge_good_morning",
        "Good morning sans charge",
        1,
        [],
        "Mains sur les hanches, amplitude moderee.",
        "Hanches en arriere.",
        20,
        45,
        "hinge_wall_touch",
        "hinge_dumbbell_deadlift",
      ),
      variant(
        "hip_hinge",
        "hinge_dumbbell_deadlift",
        "Souleve de terre leger aux halteres",
        2,
        ["dumbbells"],
        "Charges legeres, trajectoire proche des jambes.",
        "Pas d'arrondi du dos.",
        20,
        45,
        "hinge_good_morning",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une charniere de hanches.",
  }),
  exercise({
    id: "glute_bridge",
    name: "Pont fessier",
    movementPattern: "bridge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Activer la chaine posterieure au sol.",
    primaryCue: "Monte le bassin sans cambrer le bas du dos.",
    teachingSteps: [
      "Allonge-toi sur le dos, pieds au sol.",
      "Pousse dans les talons.",
      "Monte puis redescends lentement.",
    ],
    commonMistakes: ["Cambrer excessivement", "Pousser trop fort dans la nuque"],
    breathing: "Expire en montant le bassin.",
    requiredEquipment: [],
    targetZones: ["hips", "back"],
    cautionZones: ["back", "hips"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "glute_bridge",
        "glute_bridge_short",
        "Pont fessier amplitude courte",
        0,
        [],
        "Monte peu, cherche surtout le controle.",
        "Bassin stable.",
        15,
        35,
        null,
        "glute_bridge_standard",
      ),
      variant(
        "glute_bridge",
        "glute_bridge_standard",
        "Pont fessier",
        1,
        [],
        "Amplitude confortable, sans cambrure.",
        "Talons ancres.",
        20,
        45,
        "glute_bridge_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un pont fessier.",
  }),
  exercise({
    id: "dead_bug",
    name: "Dead bug adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Stabiliser la sangle abdominale sans flexions rapides.",
    primaryCue: "Garde le bas du dos calme et le mouvement lent.",
    teachingSteps: [
      "Allonge-toi sur le dos.",
      "Bouge un bras ou une jambe a la fois.",
      "Reviens au centre avant de changer de cote.",
    ],
    commonMistakes: ["Aller vite", "Perdre le controle du bas du dos"],
    breathing: "Expire pendant l'extension du membre.",
    requiredEquipment: [],
    targetZones: ["back", "hips"],
    cautionZones: ["back", "hips"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "dead_bug",
        "dead_bug_heel_tap",
        "Touches talon alternees",
        0,
        [],
        "Garde les pieds proches du sol.",
        "Lent et controle.",
        15,
        35,
        null,
        "dead_bug_standard",
      ),
      variant(
        "dead_bug",
        "dead_bug_standard",
        "Dead bug alterne",
        1,
        [],
        "Bras et jambe opposes, amplitude courte si besoin.",
        "Bas du dos calme.",
        20,
        45,
        "dead_bug_heel_tap",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un dead bug adapte.",
  }),
  exercise({
    id: "plank_family",
    name: "Gainage adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Tenir une position stable sans chercher l'echec.",
    primaryCue: "Reste solide, arrete avant de compenser.",
    teachingSteps: [
      "Choisis le support adapte.",
      "Aligne tete, buste et bassin.",
      "Respire pendant toute la tenue.",
    ],
    commonMistakes: ["Bloquer la respiration", "Laisser le bassin tomber"],
    breathing: "Respiration courte et reguliere.",
    requiredEquipment: [],
    targetZones: ["back", "shoulders", "wrists"],
    cautionZones: ["back", "shoulders", "wrists"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 45,
    variants: [
      variant(
        "plank_family",
        "plank_wall",
        "Gainage debout contre un mur",
        0,
        [],
        "Mains au mur, corps incline legerement.",
        "Respire sans bloquer.",
        10,
        30,
        null,
        "plank_incline",
      ),
      variant(
        "plank_family",
        "plank_incline",
        "Gainage incline",
        1,
        ["stable_chair"],
        "Avant-bras ou mains sur un support stable.",
        "Bassin aligne.",
        15,
        40,
        "plank_wall",
        "plank_knees",
      ),
      variant(
        "plank_family",
        "plank_knees",
        "Gainage sur les genoux",
        2,
        [],
        "Genoux au sol, bassin stable.",
        "Arrete avant tremblement excessif.",
        15,
        45,
        "plank_incline",
        "plank_full",
      ),
      variant(
        "plank_family",
        "plank_full",
        "Gainage classique",
        3,
        [],
        "Position planche, tenue courte et propre.",
        "Qualite avant duree.",
        15,
        45,
        "plank_knees",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un gainage adapte.",
  }),
  exercise({
    id: "bird_dog",
    name: "Bird-dog adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Travailler la stabilite du tronc et des hanches.",
    primaryCue: "Allonge-toi dans l'axe sans tourner le bassin.",
    teachingSteps: [
      "Pars a quatre pattes ou debout selon la variante.",
      "Allonge lentement un bras ou une jambe.",
      "Reviens au centre avant de changer.",
    ],
    commonMistakes: ["Monter trop haut", "Tourner le bassin"],
    breathing: "Expire pendant l'allongement.",
    requiredEquipment: [],
    targetZones: ["back", "hips", "shoulders"],
    cautionZones: ["back", "hips", "wrists", "shoulders"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "bird_dog",
        "bird_dog_standing",
        "Extension debout alternee",
        0,
        [],
        "Debout, allonge une jambe vers l'arriere sans pencher.",
        "Buste stable.",
        15,
        35,
        null,
        "bird_dog_quadruped",
      ),
      variant(
        "bird_dog",
        "bird_dog_quadruped",
        "Bird-dog au sol",
        1,
        [],
        "A quatre pattes, allonge bras et jambe opposes.",
        "Bassin stable.",
        20,
        45,
        "bird_dog_standing",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un bird-dog adapte.",
  }),
  exercise({
    id: "band_row",
    name: "Tirage avec elastique",
    movementPattern: "pull",
    capabilityDimension: "upper_pull",
    shortDescription: "Ajouter un tirage quand le materiel le permet.",
    primaryCue: "Tire les coudes vers l'arriere sans hausser les epaules.",
    teachingSteps: [
      "Fixe ou tiens l'elastique de facon sure.",
      "Grandis-toi avant de tirer.",
      "Reviens lentement bras tendus.",
    ],
    commonMistakes: ["Tirer avec la nuque", "Relacher d'un coup"],
    breathing: "Expire en tirant.",
    requiredEquipment: ["resistance_band"],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders", "back"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "band_row",
        "band_row_light",
        "Tirage elastique leger",
        1,
        ["resistance_band"],
        "Tension legere, retour controle.",
        "Epaules basses.",
        15,
        40,
        null,
        "band_row_standard",
      ),
      variant(
        "band_row",
        "band_row_standard",
        "Tirage elastique",
        2,
        ["resistance_band"],
        "Tension moderee, pas d'a-coup.",
        "Coudes vers l'arriere.",
        20,
        45,
        "band_row_light",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un tirage avec elastique.",
  }),
  exercise({
    id: "farmer_carry",
    name: "Port de charges leger",
    movementPattern: "locomotion",
    capabilityDimension: "posterior_chain",
    shortDescription: "Marcher avec des charges legeres et controlees.",
    primaryCue: "Reste grand, marche lentement et pose les charges si besoin.",
    teachingSteps: [
      "Prends deux charges faciles a controler.",
      "Tiens-toi droit.",
      "Marche lentement puis repose les charges avec controle.",
    ],
    commonMistakes: ["Choisir trop lourd", "Se pencher d'un cote"],
    breathing: "Respiration continue.",
    requiredEquipment: ["dumbbells"],
    targetZones: ["back", "shoulders", "hips"],
    cautionZones: ["back", "shoulders", "wrists"],
    difficulty: 2,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "farmer_carry",
        "farmer_carry_light",
        "Port de charges leger",
        2,
        ["dumbbells"],
        "Charges faciles, distance courte.",
        "Posture grande.",
        15,
        40,
        null,
        "farmer_carry_standard",
      ),
      variant(
        "farmer_carry",
        "farmer_carry_standard",
        "Port de charges controle",
        3,
        ["dumbbells"],
        "Charges moderees, marche stable.",
        "Pose avant fatigue.",
        20,
        45,
        "farmer_carry_light",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un port de charges leger.",
  }),
];

export function getExerciseById(exerciseId: string): Exercise | null {
  return STRENGTH_EXERCISES.find((exerciseItem) => exerciseItem.id === exerciseId) ?? null;
}

export function getVariantById(variantId: string): ExerciseVariant | null {
  for (const exerciseItem of STRENGTH_EXERCISES) {
    const found = exerciseItem.variants.find((item) => item.id === variantId);
    if (found) {
      return found;
    }
  }

  return null;
}
