import type {
  BodyZone,
  CapabilityDimension,
  CapabilityLevel,
  EquipmentType,
  Exercise,
  ExerciseMedia,
  ExerciseVariant,
  MovementPattern,
} from "@/lib/sport/types";

function media(exerciseId: string, altText: string): ExerciseMedia[] {
  return [
    {
      id: `${exerciseId}-media-placeholder`,
      exerciseId,
      kind: "illustration",
      placeholder: true,
      altText,
      source: "Emplacement reserve, aucun media externe importe.",
      license: "A fournir avant publication du media.",
      validationStatus: "draft_unreviewed",
    },
  ];
}

function variant(
  exerciseId: string,
  id: string,
  name: string,
  difficulty: CapabilityLevel,
  requiredEquipment: EquipmentType[],
  guidance: string,
  primaryCue: string,
  effortSecondsMin: number,
  effortSecondsMax: number,
  easierVariantId: string | null,
  harderVariantId: string | null,
): ExerciseVariant {
  return {
    id,
    exerciseId,
    name,
    difficulty,
    requiredEquipment,
    guidance,
    primaryCue,
    effortSecondsMin,
    effortSecondsMax,
    easierVariantId,
    harderVariantId,
  };
}

function exercise(args: {
  id: string;
  name: string;
  movementPattern: MovementPattern;
  capabilityDimension: CapabilityDimension;
  shortDescription: string;
  primaryCue: string;
  teachingSteps: string[];
  commonMistakes: string[];
  breathing: string;
  requiredEquipment: EquipmentType[];
  targetZones: BodyZone[];
  cautionZones: BodyZone[];
  difficulty: CapabilityLevel;
  effortSecondsMin: number;
  effortSecondsMax: number;
  variants: ExerciseVariant[];
  mediaAlt: string;
}): Exercise {
  return {
    id: args.id,
    name: args.name,
    activity: "strength",
    movementPattern: args.movementPattern,
    capabilityDimension: args.capabilityDimension,
    shortDescription: args.shortDescription,
    primaryCue: args.primaryCue,
    teachingSteps: args.teachingSteps,
    commonMistakes: args.commonMistakes,
    breathing: args.breathing,
    requiredEquipment: args.requiredEquipment,
    targetZones: args.targetZones,
    cautionZones: args.cautionZones,
    difficulty: args.difficulty,
    effortSecondsMin: args.effortSecondsMin,
    effortSecondsMax: args.effortSecondsMax,
    active: true,
    validationStatus: "draft_unreviewed",
    variants: args.variants,
    media: media(args.id, args.mediaAlt),
  };
}

export const STRENGTH_EXERCISES: Exercise[] = [
  exercise({
    id: "warmup_march",
    name: "Marche active sur place",
    movementPattern: "mobility",
    capabilityDimension: "cardio_endurance",
    shortDescription: "Elever progressivement le rythme sans impact.",
    primaryCue: "Garde une respiration facile et les appuis souples.",
    teachingSteps: [
      "Tiens-toi droit.",
      "Monte les genoux sans chercher la hauteur maximale.",
      "Balance naturellement les bras.",
    ],
    commonMistakes: ["Bloquer la respiration", "Taper fortement les pieds"],
    breathing: "Respiration naturelle, capable de parler.",
    requiredEquipment: [],
    targetZones: ["hips", "ankles"],
    cautionZones: ["ankles", "knees"],
    difficulty: 0,
    effortSecondsMin: 20,
    effortSecondsMax: 60,
    variants: [
      variant(
        "warmup_march",
        "warmup_march_easy",
        "Marche lente sur place",
        0,
        [],
        "Reste sur un rythme tres confortable.",
        "Appuis silencieux.",
        20,
        45,
        null,
        "warmup_march_active",
      ),
      variant(
        "warmup_march",
        "warmup_march_active",
        "Marche active sur place",
        1,
        [],
        "Ajoute un leger mouvement des bras.",
        "Respiration controlee.",
        30,
        60,
        "warmup_march_easy",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une marche active sur place.",
  }),
  exercise({
    id: "mobility_shoulders",
    name: "Mobilite des epaules",
    movementPattern: "mobility",
    capabilityDimension: "mobility",
    shortDescription: "Mobiliser doucement les epaules avant les efforts.",
    primaryCue: "Reste dans une amplitude confortable.",
    teachingSteps: [
      "Relache la nuque.",
      "Dessine de petits cercles avec les epaules.",
      "Inverse le sens sans forcer.",
    ],
    commonMistakes: ["Monter les epaules vers les oreilles", "Chercher une amplitude douloureuse"],
    breathing: "Expire pendant les cercles vers l'arriere.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders"],
    difficulty: 0,
    effortSecondsMin: 20,
    effortSecondsMax: 45,
    variants: [
      variant(
        "mobility_shoulders",
        "mobility_shoulders_small",
        "Cercles d'epaules courts",
        0,
        [],
        "Fais des cercles courts, lents et confortables.",
        "Aucune douleur recherchee.",
        20,
        40,
        null,
        "mobility_shoulders_full",
      ),
      variant(
        "mobility_shoulders",
        "mobility_shoulders_full",
        "Mobilite epaules complete",
        1,
        [],
        "Augmente seulement si le mouvement reste fluide.",
        "Nuque longue.",
        25,
        45,
        "mobility_shoulders_small",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une mobilisation douce des epaules.",
  }),
  exercise({
    id: "bodyweight_squat",
    name: "Demi-squat controle",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Renforcer les jambes avec une amplitude prudente.",
    primaryCue: "Pousse le sol et garde les genoux dans l'axe.",
    teachingSteps: [
      "Place les pieds a largeur confortable.",
      "Descends peu profond, comme vers une chaise imaginaire.",
      "Remonte sans a-coup.",
    ],
    commonMistakes: ["Descendre trop bas trop vite", "Laisser les genoux rentrer"],
    breathing: "Inspire en descendant, expire en remontant.",
    requiredEquipment: [],
    targetZones: ["knees", "hips"],
    cautionZones: ["knees", "hips", "ankles"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 40,
    variants: [
      variant(
        "bodyweight_squat",
        "bodyweight_squat_partial",
        "Demi-squat tres court",
        0,
        [],
        "Amplitude courte, mains libres ou posees sur les hanches.",
        "Mouvement lent.",
        15,
        30,
        null,
        "bodyweight_squat_controlled",
      ),
      variant(
        "bodyweight_squat",
        "bodyweight_squat_controlled",
        "Demi-squat controle",
        1,
        [],
        "Descends un peu plus si tout reste confortable.",
        "Genoux dans l'axe.",
        20,
        40,
        "bodyweight_squat_partial",
        "bodyweight_squat_deeper",
      ),
      variant(
        "bodyweight_squat",
        "bodyweight_squat_deeper",
        "Squat poids du corps adapte",
        2,
        [],
        "Amplitude moderee, toujours sans douleur.",
        "Buste stable.",
        25,
        45,
        "bodyweight_squat_controlled",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un demi-squat controle.",
  }),
  exercise({
    id: "sit_to_stand",
    name: "Assis-debout depuis une chaise",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Travailler les jambes avec un repere stable.",
    primaryCue: "Leve-toi en poussant dans les pieds.",
    teachingSteps: [
      "Assieds-toi au bord d'une chaise stable.",
      "Penche legerement le buste.",
      "Leve-toi puis reviens t'asseoir avec controle.",
    ],
    commonMistakes: ["Se laisser tomber sur la chaise", "Utiliser l'elan"],
    breathing: "Expire en te levant.",
    requiredEquipment: ["stable_chair"],
    targetZones: ["knees", "hips"],
    cautionZones: ["knees", "hips"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "sit_to_stand",
        "sit_to_stand_with_support",
        "Assis-debout avec appui",
        0,
        ["stable_chair"],
        "Utilise les mains legerement si necessaire.",
        "Controle la descente.",
        15,
        35,
        null,
        "sit_to_stand_no_hands",
      ),
      variant(
        "sit_to_stand",
        "sit_to_stand_no_hands",
        "Assis-debout sans les mains",
        1,
        ["stable_chair"],
        "Mains libres, rythme calme.",
        "Pieds bien ancres.",
        20,
        45,
        "sit_to_stand_with_support",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un assis-debout depuis une chaise.",
  }),
  exercise({
    id: "push_up_family",
    name: "Pompes adaptees",
    movementPattern: "push",
    capabilityDimension: "upper_push",
    shortDescription: "Poussee du haut du corps avec variante ajustee.",
    primaryCue: "Garde le corps solide et pousse sans bloquer la respiration.",
    teachingSteps: [
      "Place les mains sous ou legerement devant les epaules.",
      "Descends dans une amplitude confortable.",
      "Repousse le support sans creuser le dos.",
    ],
    commonMistakes: ["Creuser le bas du dos", "Hausser les epaules", "Aller jusqu'a l'echec"],
    breathing: "Inspire en descendant, expire en poussant.",
    requiredEquipment: [],
    targetZones: ["shoulders", "wrists"],
    cautionZones: ["shoulders", "wrists", "back"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 45,
    variants: [
      variant(
        "push_up_family",
        "push_wall",
        "Pompes contre un mur",
        0,
        [],
        "Place-toi face a un mur, pieds recules.",
        "Pousse le mur calmement.",
        10,
        35,
        null,
        "push_knees",
      ),
      variant(
        "push_up_family",
        "push_incline",
        "Pompes inclinees",
        1,
        ["stable_chair"],
        "Mains sur une chaise stable ou un support fixe.",
        "Corps aligne.",
        15,
        40,
        "push_wall",
        "push_standard",
      ),
      variant(
        "push_up_family",
        "push_knees",
        "Pompes sur les genoux",
        2,
        [],
        "Genoux au sol, mains sous les epaules.",
        "Descente controlee.",
        15,
        45,
        "push_wall",
        "push_standard",
      ),
      variant(
        "push_up_family",
        "push_standard",
        "Pompes classiques",
        3,
        [],
        "Position planche, amplitude confortable.",
        "Ne cherche pas l'echec.",
        15,
        45,
        "push_knees",
        "push_feet_elevated",
      ),
      variant(
        "push_up_family",
        "push_feet_elevated",
        "Pompes pieds sureleves",
        4,
        [],
        "Pieds poses plus haut que les mains, seulement si la pompe classique reste facile.",
        "Garde le meme controle.",
        15,
        45,
        "push_standard",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une variante de pompe adaptee.",
  }),
  exercise({
    id: "hip_hinge",
    name: "Charniere de hanches",
    movementPattern: "hinge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Apprendre le mouvement de hanches sans charge.",
    primaryCue: "Recule les hanches en gardant le dos long.",
    teachingSteps: [
      "Pieds stables, genoux legerement souples.",
      "Recule les hanches comme pour toucher un mur.",
      "Reviens debout en serrant legerement les fessiers.",
    ],
    commonMistakes: ["Arrondir le dos", "Transformer le geste en squat"],
    breathing: "Inspire en reculant les hanches, expire en revenant.",
    requiredEquipment: [],
    targetZones: ["hips", "back"],
    cautionZones: ["back", "hips"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "hip_hinge",
        "hinge_wall_touch",
        "Charniere vers un mur",
        0,
        [],
        "Recule doucement les hanches vers un mur proche.",
        "Dos long.",
        15,
        35,
        null,
        "hinge_good_morning",
      ),
      variant(
        "hip_hinge",
        "hinge_good_morning",
        "Good morning sans charge",
        1,
        [],
        "Mains sur les hanches, amplitude moderee.",
        "Hanches en arriere.",
        20,
        45,
        "hinge_wall_touch",
        "hinge_dumbbell_deadlift",
      ),
      variant(
        "hip_hinge",
        "hinge_dumbbell_deadlift",
        "Souleve de terre leger aux halteres",
        2,
        ["dumbbells"],
        "Charges legeres, trajectoire proche des jambes.",
        "Pas d'arrondi du dos.",
        20,
        45,
        "hinge_good_morning",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une charniere de hanches.",
  }),
  exercise({
    id: "glute_bridge",
    name: "Pont fessier",
    movementPattern: "bridge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Activer la chaine posterieure au sol.",
    primaryCue: "Monte le bassin sans cambrer le bas du dos.",
    teachingSteps: [
      "Allonge-toi sur le dos, pieds au sol.",
      "Pousse dans les talons.",
      "Monte puis redescends lentement.",
    ],
    commonMistakes: ["Cambrer excessivement", "Pousser trop fort dans la nuque"],
    breathing: "Expire en montant le bassin.",
    requiredEquipment: [],
    targetZones: ["hips", "back"],
    cautionZones: ["back", "hips"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "glute_bridge",
        "glute_bridge_short",
        "Pont fessier amplitude courte",
        0,
        [],
        "Monte peu, cherche surtout le controle.",
        "Bassin stable.",
        15,
        35,
        null,
        "glute_bridge_standard",
      ),
      variant(
        "glute_bridge",
        "glute_bridge_standard",
        "Pont fessier",
        1,
        [],
        "Amplitude confortable, sans cambrure.",
        "Talons ancres.",
        20,
        45,
        "glute_bridge_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un pont fessier.",
  }),
  exercise({
    id: "dead_bug",
    name: "Dead bug adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Stabiliser la sangle abdominale sans flexions rapides.",
    primaryCue: "Garde le bas du dos calme et le mouvement lent.",
    teachingSteps: [
      "Allonge-toi sur le dos.",
      "Bouge un bras ou une jambe a la fois.",
      "Reviens au centre avant de changer de cote.",
    ],
    commonMistakes: ["Aller vite", "Perdre le controle du bas du dos"],
    breathing: "Expire pendant l'extension du membre.",
    requiredEquipment: [],
    targetZones: ["back", "hips"],
    cautionZones: ["back", "hips"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "dead_bug",
        "dead_bug_heel_tap",
        "Touches talon alternees",
        0,
        [],
        "Garde les pieds proches du sol.",
        "Lent et controle.",
        15,
        35,
        null,
        "dead_bug_standard",
      ),
      variant(
        "dead_bug",
        "dead_bug_standard",
        "Dead bug alterne",
        1,
        [],
        "Bras et jambe opposes, amplitude courte si besoin.",
        "Bas du dos calme.",
        20,
        45,
        "dead_bug_heel_tap",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un dead bug adapte.",
  }),
  exercise({
    id: "plank_family",
    name: "Gainage adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Tenir une position stable sans chercher l'echec.",
    primaryCue: "Reste solide, arrete avant de compenser.",
    teachingSteps: [
      "Choisis le support adapte.",
      "Aligne tete, buste et bassin.",
      "Respire pendant toute la tenue.",
    ],
    commonMistakes: ["Bloquer la respiration", "Laisser le bassin tomber"],
    breathing: "Respiration courte et reguliere.",
    requiredEquipment: [],
    targetZones: ["back", "shoulders", "wrists"],
    cautionZones: ["back", "shoulders", "wrists"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 45,
    variants: [
      variant(
        "plank_family",
        "plank_wall",
        "Gainage debout contre un mur",
        0,
        [],
        "Mains au mur, corps incline legerement.",
        "Respire sans bloquer.",
        10,
        30,
        null,
        "plank_incline",
      ),
      variant(
        "plank_family",
        "plank_incline",
        "Gainage incline",
        1,
        ["stable_chair"],
        "Avant-bras ou mains sur un support stable.",
        "Bassin aligne.",
        15,
        40,
        "plank_wall",
        "plank_knees",
      ),
      variant(
        "plank_family",
        "plank_knees",
        "Gainage sur les genoux",
        2,
        [],
        "Genoux au sol, bassin stable.",
        "Arrete avant tremblement excessif.",
        15,
        45,
        "plank_incline",
        "plank_full",
      ),
      variant(
        "plank_family",
        "plank_full",
        "Gainage classique",
        3,
        [],
        "Position planche, tenue courte et propre.",
        "Qualite avant duree.",
        15,
        45,
        "plank_knees",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un gainage adapte.",
  }),
  exercise({
    id: "bird_dog",
    name: "Bird-dog adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Travailler la stabilite du tronc et des hanches.",
    primaryCue: "Allonge-toi dans l'axe sans tourner le bassin.",
    teachingSteps: [
      "Pars a quatre pattes ou debout selon la variante.",
      "Allonge lentement un bras ou une jambe.",
      "Reviens au centre avant de changer.",
    ],
    commonMistakes: ["Monter trop haut", "Tourner le bassin"],
    breathing: "Expire pendant l'allongement.",
    requiredEquipment: [],
    targetZones: ["back", "hips", "shoulders"],
    cautionZones: ["back", "hips", "wrists", "shoulders"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "bird_dog",
        "bird_dog_standing",
        "Extension debout alternee",
        0,
        [],
        "Debout, allonge une jambe vers l'arriere sans pencher.",
        "Buste stable.",
        15,
        35,
        null,
        "bird_dog_quadruped",
      ),
      variant(
        "bird_dog",
        "bird_dog_quadruped",
        "Bird-dog au sol",
        1,
        [],
        "A quatre pattes, allonge bras et jambe opposes.",
        "Bassin stable.",
        20,
        45,
        "bird_dog_standing",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un bird-dog adapte.",
  }),
  exercise({
    id: "heel_raise",
    name: "Montees sur pointes",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Renforcer les mollets et la stabilite des chevilles sans impact.",
    primaryCue: "Monte lentement, redescends sans tomber dans les talons.",
    teachingSteps: [
      "Place les pieds sous les hanches.",
      "Monte sur les pointes sans partir vers l'avant.",
      "Redescends lentement jusqu'a retrouver tout le pied au sol.",
    ],
    commonMistakes: ["Rebondir", "Laisser les chevilles partir vers l'exterieur"],
    breathing: "Expire en montant, inspire en redescendant.",
    requiredEquipment: [],
    targetZones: ["ankles", "knees"],
    cautionZones: ["ankles", "knees"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "heel_raise",
        "heel_raise_two_feet",
        "Montees sur pointes deux pieds",
        0,
        [],
        "Monte avec les deux pieds, amplitude confortable.",
        "Appui repartit.",
        15,
        35,
        null,
        "heel_raise_slow",
      ),
      variant(
        "heel_raise",
        "heel_raise_slow",
        "Montees sur pointes lentes",
        1,
        [],
        "Ajoute une descente lente, sans chercher la fatigue.",
        "Controle la descente.",
        20,
        45,
        "heel_raise_two_feet",
        "heel_raise_single_support",
      ),
      variant(
        "heel_raise",
        "heel_raise_single_support",
        "Montees sur pointe avec appui leger",
        2,
        [],
        "Allege un pied sans perdre l'equilibre.",
        "Bassin stable.",
        20,
        45,
        "heel_raise_slow",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder de montees sur pointes.",
  }),
  exercise({
    id: "reverse_lunge",
    name: "Fente arriere adaptee",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Travailler les jambes avec une amplitude progressive.",
    primaryCue: "Recule peu, garde le genou avant dans l'axe du pied.",
    teachingSteps: [
      "Pars debout, pieds sous les hanches.",
      "Pose un pied en arriere sur une distance confortable.",
      "Remonte en poussant dans le pied avant.",
    ],
    commonMistakes: ["Faire un pas trop long", "Laisser le genou avant rentrer"],
    breathing: "Inspire en reculant, expire en revenant debout.",
    requiredEquipment: [],
    targetZones: ["knees", "hips", "ankles"],
    cautionZones: ["knees", "hips", "ankles"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "reverse_lunge",
        "reverse_lunge_short",
        "Fente arriere tres courte",
        1,
        [],
        "Recule seulement un peu, sans chercher la profondeur.",
        "Genou avant stable.",
        15,
        35,
        null,
        "reverse_lunge_alternating",
      ),
      variant(
        "reverse_lunge",
        "reverse_lunge_alternating",
        "Fentes arriere alternees",
        2,
        [],
        "Alterne les jambes avec un rythme calme.",
        "Remonte sans elan.",
        20,
        45,
        "reverse_lunge_short",
        "reverse_lunge_hover",
      ),
      variant(
        "reverse_lunge",
        "reverse_lunge_hover",
        "Fente arriere avec genou suspendu",
        3,
        [],
        "Descends un peu plus si tout reste stable et confortable.",
        "Buste grand.",
        20,
        45,
        "reverse_lunge_alternating",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une fente arriere adaptee.",
  }),
  exercise({
    id: "split_squat",
    name: "Squat decale",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Renforcer une jambe a la fois avec un appui au sol stable.",
    primaryCue: "Reste dans une amplitude courte et controlee.",
    teachingSteps: [
      "Place un pied devant et un pied derriere.",
      "Plie legerement les deux genoux.",
      "Remonte sans verrouiller brutalement.",
    ],
    commonMistakes: ["Avancer le genou sans controle", "Tourner le bassin"],
    breathing: "Expire en remontant.",
    requiredEquipment: [],
    targetZones: ["knees", "hips", "ankles"],
    cautionZones: ["knees", "hips", "ankles"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "split_squat",
        "split_squat_micro",
        "Squat decale tres court",
        1,
        [],
        "Descends seulement de quelques centimetres.",
        "Appuis calmes.",
        15,
        35,
        null,
        "split_squat_controlled",
      ),
      variant(
        "split_squat",
        "split_squat_controlled",
        "Squat decale controle",
        2,
        [],
        "Augmente un peu l'amplitude si les genoux restent stables.",
        "Bassin face avant.",
        20,
        45,
        "split_squat_micro",
        "split_squat_deeper",
      ),
      variant(
        "split_squat",
        "split_squat_deeper",
        "Squat decale plus profond",
        3,
        [],
        "Descends davantage seulement si la variante controlee reste facile.",
        "Controle avant profondeur.",
        20,
        45,
        "split_squat_controlled",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un squat decale.",
  }),
  exercise({
    id: "lateral_squat_shift",
    name: "Transfert lateral",
    movementPattern: "squat",
    capabilityDimension: "legs",
    shortDescription: "Travailler jambes et hanches dans un mouvement lateral doux.",
    primaryCue: "Deplace le poids sans laisser le genou s'effondrer.",
    teachingSteps: [
      "Ecarte les pieds un peu plus que les hanches.",
      "Deplace le bassin vers un cote.",
      "Reviens au centre avant de changer.",
    ],
    commonMistakes: ["Aller trop bas", "Tourner le pied d'appui"],
    breathing: "Respiration continue.",
    requiredEquipment: [],
    targetZones: ["knees", "hips", "ankles"],
    cautionZones: ["knees", "hips", "ankles"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "lateral_squat_shift",
        "lateral_shift_small",
        "Transfert lateral court",
        0,
        [],
        "Deplace peu le poids, amplitude confortable.",
        "Pieds ancres.",
        15,
        35,
        null,
        "lateral_squat_partial",
      ),
      variant(
        "lateral_squat_shift",
        "lateral_squat_partial",
        "Demi-squat lateral",
        1,
        [],
        "Plie un peu plus la jambe d'appui.",
        "Genou dans l'axe.",
        20,
        45,
        "lateral_shift_small",
        "lateral_squat_deeper",
      ),
      variant(
        "lateral_squat_shift",
        "lateral_squat_deeper",
        "Squat lateral adapte",
        2,
        [],
        "Augmente l'amplitude sans chercher l'etirement maximal.",
        "Retour controle.",
        20,
        45,
        "lateral_squat_partial",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un transfert lateral.",
  }),
  exercise({
    id: "pike_push",
    name: "Poussee epaules adaptee",
    movementPattern: "push",
    capabilityDimension: "upper_push",
    shortDescription: "Introduire une poussee plus verticale sans charge externe.",
    primaryCue: "Garde la nuque longue et reduis l'amplitude au moindre doute.",
    teachingSteps: [
      "Place les mains au sol, bassin legerement haut.",
      "Transfere un peu le poids vers les mains.",
      "Plie les coudes seulement si les epaules restent confortables.",
    ],
    commonMistakes: ["Mettre trop de poids dans les mains", "Rentrer la tete"],
    breathing: "Expire en repoussant le sol.",
    requiredEquipment: [],
    targetZones: ["shoulders", "wrists", "back"],
    cautionZones: ["shoulders", "wrists", "back"],
    difficulty: 1,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "pike_push",
        "pike_weight_shift",
        "Transfert de poids epaules",
        1,
        [],
        "Transfere doucement le poids vers les mains sans plier les coudes.",
        "Nuque longue.",
        10,
        30,
        null,
        "pike_push_short",
      ),
      variant(
        "pike_push",
        "pike_push_short",
        "Poussee epaules courte",
        2,
        [],
        "Plie legerement les coudes puis repousse le sol.",
        "Amplitude courte.",
        15,
        35,
        "pike_weight_shift",
        "pike_push_controlled",
      ),
      variant(
        "pike_push",
        "pike_push_controlled",
        "Poussee epaules controlee",
        3,
        [],
        "Augmente un peu l'amplitude sans chercher l'echec.",
        "Epaules basses.",
        15,
        40,
        "pike_push_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une poussee epaules adaptee.",
  }),
  exercise({
    id: "scapular_push",
    name: "Poussee des omoplates",
    movementPattern: "push",
    capabilityDimension: "upper_push",
    shortDescription: "Renforcer le controle des epaules sans grand mouvement de coude.",
    primaryCue: "Repousse le support en gardant les coudes presque tendus.",
    teachingSteps: [
      "Installe une position de pompe adaptee.",
      "Laisse les omoplates se rapprocher legerement.",
      "Repousse le support pour les eloigner.",
    ],
    commonMistakes: ["Plier les coudes", "Hausser les epaules"],
    breathing: "Expire en repoussant.",
    requiredEquipment: [],
    targetZones: ["shoulders", "wrists", "back"],
    cautionZones: ["shoulders", "wrists", "back"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "scapular_push",
        "scapular_wall_push",
        "Omoplates au mur",
        0,
        [],
        "Mains au mur, repousse doucement sans plier les coudes.",
        "Epaules basses.",
        10,
        30,
        null,
        "scapular_knees_push",
      ),
      variant(
        "scapular_push",
        "scapular_knees_push",
        "Omoplates sur les genoux",
        1,
        [],
        "Position genoux au sol, petit mouvement d'omoplates.",
        "Coudes longs.",
        15,
        35,
        "scapular_wall_push",
        "scapular_plank_push",
      ),
      variant(
        "scapular_push",
        "scapular_plank_push",
        "Omoplates en planche",
        2,
        [],
        "Position planche courte, mouvement lent.",
        "Tronc stable.",
        15,
        40,
        "scapular_knees_push",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une poussee des omoplates.",
  }),
  exercise({
    id: "quadruped_triceps_press",
    name: "Poussee triceps au sol",
    movementPattern: "push",
    capabilityDimension: "upper_push",
    shortDescription: "Renforcer les bras avec une charge corporelle reduite.",
    primaryCue: "Plie peu les coudes et garde les epaules loin des oreilles.",
    teachingSteps: [
      "Place-toi a quatre pattes.",
      "Avance legerement les mains.",
      "Plie puis tends les coudes sur une petite amplitude.",
    ],
    commonMistakes: ["Descendre trop bas", "Basculer tout le poids dans les poignets"],
    breathing: "Expire en poussant.",
    requiredEquipment: [],
    targetZones: ["shoulders", "wrists"],
    cautionZones: ["shoulders", "wrists", "back"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "quadruped_triceps_press",
        "quadruped_triceps_shift",
        "Transfert triceps a quatre pattes",
        0,
        [],
        "Deplace legerement le buste vers l'avant puis reviens.",
        "Poignets calmes.",
        10,
        30,
        null,
        "quadruped_triceps_press_short",
      ),
      variant(
        "quadruped_triceps_press",
        "quadruped_triceps_press_short",
        "Poussee triceps courte",
        1,
        [],
        "Plie un peu les coudes puis repousse le sol.",
        "Amplitude propre.",
        15,
        40,
        "quadruped_triceps_shift",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une poussee triceps au sol.",
  }),
  exercise({
    id: "single_leg_hinge",
    name: "Charniere sur une jambe adaptee",
    movementPattern: "hinge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Travailler l'arriere des jambes et l'equilibre sans charge.",
    primaryCue: "Recule les hanches, garde le dos long et reduis l'amplitude si besoin.",
    teachingSteps: [
      "Garde un pied principal au sol.",
      "Recule les hanches comme une charniere.",
      "Reviens debout sans tourner le bassin.",
    ],
    commonMistakes: ["Arrondir le dos", "Chercher a lever la jambe haut"],
    breathing: "Expire en revenant debout.",
    requiredEquipment: [],
    targetZones: ["hips", "back", "ankles"],
    cautionZones: ["back", "hips", "ankles"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "single_leg_hinge",
        "kickstand_hinge_short",
        "Charniere pied bequille",
        1,
        [],
        "Garde le pied arriere en appui leger pour stabiliser.",
        "Hanches en arriere.",
        15,
        35,
        null,
        "single_leg_hinge_reach",
      ),
      variant(
        "single_leg_hinge",
        "single_leg_hinge_reach",
        "Charniere une jambe courte",
        2,
        [],
        "Allege la jambe arriere et avance le buste peu a peu.",
        "Bassin stable.",
        20,
        45,
        "kickstand_hinge_short",
        "single_leg_hinge_airplane_short",
      ),
      variant(
        "single_leg_hinge",
        "single_leg_hinge_airplane_short",
        "Charniere une jambe avec ouverture courte",
        3,
        [],
        "Ouvre tres legerement le bassin puis reviens dans l'axe.",
        "Controle avant amplitude.",
        20,
        45,
        "single_leg_hinge_reach",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une charniere sur une jambe.",
  }),
  exercise({
    id: "hamstring_walkout",
    name: "Marche des talons au sol",
    movementPattern: "hinge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Renforcer l'arriere des jambes depuis une position de pont.",
    primaryCue: "Garde le bassin controle et avance seulement si le dos reste calme.",
    teachingSteps: [
      "Pars en pont fessier confortable.",
      "Avance un talon puis l'autre de quelques centimetres.",
      "Ramene les pieds avant de reposer le bassin.",
    ],
    commonMistakes: ["Laisser le bassin tomber", "Aller trop loin trop vite"],
    breathing: "Respire de facon continue pendant les petits pas.",
    requiredEquipment: [],
    targetZones: ["hips", "back", "knees"],
    cautionZones: ["back", "hips", "knees"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 40,
    variants: [
      variant(
        "hamstring_walkout",
        "bridge_heel_walk_small",
        "Petits pas de talons",
        1,
        [],
        "Avance les talons tres peu, bassin stable.",
        "Pas courts.",
        15,
        30,
        null,
        "hamstring_walkout_short",
      ),
      variant(
        "hamstring_walkout",
        "hamstring_walkout_short",
        "Marche des talons courte",
        2,
        [],
        "Fais deux ou trois petits pas avant de revenir.",
        "Bassin haut.",
        15,
        40,
        "bridge_heel_walk_small",
        "hamstring_walkout_long",
      ),
      variant(
        "hamstring_walkout",
        "hamstring_walkout_long",
        "Marche des talons controlee",
        3,
        [],
        "Allonge un peu les pas seulement si le bassin reste stable.",
        "Dos calme.",
        20,
        40,
        "hamstring_walkout_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une marche des talons au sol.",
  }),
  exercise({
    id: "hip_thrust_floor",
    name: "Extension de hanches au sol",
    movementPattern: "bridge",
    capabilityDimension: "posterior_chain",
    shortDescription: "Renforcer les hanches avec des variantes de pont sans charge.",
    primaryCue: "Monte le bassin en gardant les cotes calmes.",
    teachingSteps: [
      "Allonge-toi sur le dos, pieds au sol.",
      "Monte le bassin sans cambrer.",
      "Marque un temps court puis redescends lentement.",
    ],
    commonMistakes: ["Pousser dans la nuque", "Chercher trop haut"],
    breathing: "Expire en montant, inspire en redescendant.",
    requiredEquipment: [],
    targetZones: ["hips", "back"],
    cautionZones: ["back", "hips", "knees"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "hip_thrust_floor",
        "hip_thrust_hold_short",
        "Pont avec pause courte",
        1,
        [],
        "Tiens une seconde en haut puis redescends.",
        "Cotes basses.",
        15,
        35,
        null,
        "hip_thrust_march",
      ),
      variant(
        "hip_thrust_floor",
        "hip_thrust_march",
        "Pont avec marche alternee",
        2,
        [],
        "En haut du pont, allege un pied puis l'autre.",
        "Bassin horizontal.",
        15,
        40,
        "hip_thrust_hold_short",
        "hip_thrust_single_leg_short",
      ),
      variant(
        "hip_thrust_floor",
        "hip_thrust_single_leg_short",
        "Pont une jambe court",
        3,
        [],
        "Garde une jambe allegee et monte sur une amplitude courte.",
        "Hanches stables.",
        15,
        40,
        "hip_thrust_march",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une extension de hanches au sol.",
  }),
  exercise({
    id: "side_plank_family",
    name: "Gainage lateral adapte",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Travailler la stabilite laterale du tronc sans rotation brusque.",
    primaryCue: "Garde le bassin aligne et respire sans bloquer.",
    teachingSteps: [
      "Installe une version adaptee sur mur, genoux ou pieds.",
      "Aligne tete, buste et bassin.",
      "Tiens court puis relache proprement.",
    ],
    commonMistakes: ["Laisser le bassin tomber", "Bloquer la respiration"],
    breathing: "Respiration continue et courte.",
    requiredEquipment: [],
    targetZones: ["back", "shoulders", "hips"],
    cautionZones: ["back", "shoulders", "hips", "wrists"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "side_plank_family",
        "side_plank_wall",
        "Gainage lateral au mur",
        0,
        [],
        "Avant-bras au mur, corps legerement incline.",
        "Bassin aligne.",
        10,
        30,
        null,
        "side_plank_knees",
      ),
      variant(
        "side_plank_family",
        "side_plank_knees",
        "Gainage lateral genoux",
        1,
        [],
        "Genoux plies, avant-bras au sol.",
        "Hanches hautes.",
        10,
        35,
        "side_plank_wall",
        "side_plank_short",
      ),
      variant(
        "side_plank_family",
        "side_plank_short",
        "Gainage lateral court",
        2,
        [],
        "Jambes presque tendues, tenue courte.",
        "Respire.",
        10,
        40,
        "side_plank_knees",
        "side_plank_full",
      ),
      variant(
        "side_plank_family",
        "side_plank_full",
        "Gainage lateral classique",
        3,
        [],
        "Jambes tendues, qualite avant duree.",
        "Bassin stable.",
        10,
        40,
        "side_plank_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un gainage lateral adapte.",
  }),
  exercise({
    id: "bear_hold",
    name: "Gainage quadrupedique",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Stabiliser le tronc avec les genoux proches du sol.",
    primaryCue: "Souleve peu les genoux et garde le dos calme.",
    teachingSteps: [
      "Place-toi a quatre pattes.",
      "Rentre doucement les appuis dans le sol.",
      "Souleve ou allege les genoux selon la variante.",
    ],
    commonMistakes: ["Monter les hanches trop haut", "Bloquer le souffle"],
    breathing: "Respiration courte et reguliere.",
    requiredEquipment: [],
    targetZones: ["back", "hips", "shoulders", "wrists"],
    cautionZones: ["back", "hips", "shoulders", "wrists"],
    difficulty: 1,
    effortSecondsMin: 10,
    effortSecondsMax: 35,
    variants: [
      variant(
        "bear_hold",
        "bear_weight_shift",
        "Transfert a quatre pattes",
        1,
        [],
        "Garde les genoux au sol et transfere legerement le poids.",
        "Dos calme.",
        10,
        30,
        null,
        "bear_hover_short",
      ),
      variant(
        "bear_hold",
        "bear_hover_short",
        "Bear hold court",
        2,
        [],
        "Souleve les genoux de quelques centimetres.",
        "Genoux proches du sol.",
        10,
        35,
        "bear_weight_shift",
        "bear_shoulder_tap",
      ),
      variant(
        "bear_hold",
        "bear_shoulder_tap",
        "Bear hold avec toucher epaule",
        3,
        [],
        "Touche lentement une epaule sans tourner le bassin.",
        "Bassin stable.",
        10,
        35,
        "bear_hover_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un gainage quadrupedique.",
  }),
  exercise({
    id: "hollow_hold",
    name: "Gainage dos au sol",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Apprendre l'anti-extension sans mouvement rapide.",
    primaryCue: "Garde le bas du dos calme et choisis une version courte.",
    teachingSteps: [
      "Allonge-toi sur le dos.",
      "Rapproche legerement les cotes du bassin.",
      "Allonge un membre seulement si le dos reste stable.",
    ],
    commonMistakes: ["Cambrer", "Retenir la respiration"],
    breathing: "Expire doucement pendant l'allongement.",
    requiredEquipment: [],
    targetZones: ["back", "hips"],
    cautionZones: ["back", "hips"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 35,
    variants: [
      variant(
        "hollow_hold",
        "hollow_breathing",
        "Respiration dos au sol",
        0,
        [],
        "Garde les pieds au sol et respire sans cambrer.",
        "Dos calme.",
        10,
        30,
        null,
        "hollow_one_leg",
      ),
      variant(
        "hollow_hold",
        "hollow_one_leg",
        "Gainage une jambe allongee",
        1,
        [],
        "Allonge une jambe puis reviens avant de changer.",
        "Cotes basses.",
        10,
        35,
        "hollow_breathing",
        "hollow_hold_short",
      ),
      variant(
        "hollow_hold",
        "hollow_hold_short",
        "Hollow hold court",
        2,
        [],
        "Allonge bras ou jambes sur une tenue courte.",
        "Qualite avant duree.",
        10,
        35,
        "hollow_one_leg",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un gainage dos au sol.",
  }),
  exercise({
    id: "anti_rotation_reach",
    name: "Stabilite anti-rotation",
    movementPattern: "core",
    capabilityDimension: "core",
    shortDescription: "Limiter les rotations parasites du bassin et du tronc.",
    primaryCue: "Leve une main lentement sans tourner le bassin.",
    teachingSteps: [
      "Installe une base stable.",
      "Allege une main ou touche une epaule.",
      "Repose avant de changer de cote.",
    ],
    commonMistakes: ["Balancer le bassin", "Aller vite"],
    breathing: "Expire pendant le toucher.",
    requiredEquipment: [],
    targetZones: ["back", "hips", "shoulders", "wrists"],
    cautionZones: ["back", "hips", "shoulders", "wrists"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 35,
    variants: [
      variant(
        "anti_rotation_reach",
        "quadruped_hand_lift",
        "Main allegee a quatre pattes",
        0,
        [],
        "Allege une main sans quitter totalement l'appui si besoin.",
        "Bassin immobile.",
        10,
        30,
        null,
        "quadruped_shoulder_tap",
      ),
      variant(
        "anti_rotation_reach",
        "quadruped_shoulder_tap",
        "Touche epaule a quatre pattes",
        1,
        [],
        "Touche l'epaule opposee sans tourner.",
        "Lent.",
        10,
        35,
        "quadruped_hand_lift",
        "plank_shoulder_tap_slow",
      ),
      variant(
        "anti_rotation_reach",
        "plank_shoulder_tap_slow",
        "Touche epaule en planche",
        3,
        [],
        "En planche, touche une epaule a la fois tres lentement.",
        "Bassin stable.",
        10,
        35,
        "quadruped_shoulder_tap",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une stabilite anti-rotation.",
  }),
  exercise({
    id: "prone_w_raise",
    name: "Retraction dorsale au sol",
    movementPattern: "pull",
    capabilityDimension: "upper_pull",
    shortDescription: "Alternative de tirage sans materiel centree sur les omoplates.",
    primaryCue: "Rapproche doucement les omoplates sans tirer dans la nuque.",
    teachingSteps: [
      "Allonge-toi sur le ventre, front neutre.",
      "Ramene les coudes vers les cotes.",
      "Relache lentement sans a-coup.",
    ],
    commonMistakes: ["Cambrer fort", "Hausser les epaules"],
    breathing: "Expire pendant la retraction.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders", "back"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "prone_w_raise",
        "prone_scapular_set",
        "Omoplates serrees au sol",
        0,
        [],
        "Rapproche les omoplates sans lever les bras haut.",
        "Nuque longue.",
        10,
        30,
        null,
        "prone_w_raise_short",
      ),
      variant(
        "prone_w_raise",
        "prone_w_raise_short",
        "W au sol court",
        1,
        [],
        "Forme un W avec les bras et leve peu.",
        "Epaules basses.",
        15,
        35,
        "prone_scapular_set",
        "prone_w_raise_hold",
      ),
      variant(
        "prone_w_raise",
        "prone_w_raise_hold",
        "W au sol avec pause",
        2,
        [],
        "Ajoute une pause courte en haut.",
        "Pas de cambrure.",
        15,
        40,
        "prone_w_raise_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une retraction dorsale au sol.",
  }),
  exercise({
    id: "reverse_snow_angel",
    name: "Ange inverse au sol",
    movementPattern: "pull",
    capabilityDimension: "upper_pull",
    shortDescription: "Mobiliser et renforcer doucement le haut du dos sans materiel.",
    primaryCue: "Glisse les bras lentement, epaules loin des oreilles.",
    teachingSteps: [
      "Allonge-toi sur le ventre.",
      "Deplace les bras sur les cotes dans une amplitude courte.",
      "Reviens sans forcer les epaules.",
    ],
    commonMistakes: ["Aller vite", "Chercher une amplitude douloureuse"],
    breathing: "Respiration continue.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders", "back"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "reverse_snow_angel",
        "reverse_snow_angel_short",
        "Ange inverse court",
        0,
        [],
        "Amplitude reduite, front neutre.",
        "Epaules basses.",
        10,
        30,
        null,
        "reverse_snow_angel_controlled",
      ),
      variant(
        "reverse_snow_angel",
        "reverse_snow_angel_controlled",
        "Ange inverse controle",
        1,
        [],
        "Glisse les bras plus loin si tout reste confortable.",
        "Mouvement lent.",
        15,
        40,
        "reverse_snow_angel_short",
        "reverse_snow_angel_hover",
      ),
      variant(
        "reverse_snow_angel",
        "reverse_snow_angel_hover",
        "Ange inverse bras allege",
        2,
        [],
        "Deplace les bras legerement decolles du sol.",
        "Dos long.",
        15,
        40,
        "reverse_snow_angel_controlled",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un ange inverse au sol.",
  }),
  exercise({
    id: "wall_slide",
    name: "Glisse murale des bras",
    movementPattern: "pull",
    capabilityDimension: "upper_pull",
    shortDescription: "Travailler le controle des epaules avec le mur comme repere.",
    primaryCue: "Glisse sans douleur, garde les cotes calmes.",
    teachingSteps: [
      "Place le dos ou les avant-bras pres d'un mur.",
      "Glisse les bras vers le haut dans une amplitude confortable.",
      "Redescends lentement.",
    ],
    commonMistakes: ["Cambrer pour monter plus haut", "Forcer l'epaule"],
    breathing: "Expire en redescendant.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders", "back"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "wall_slide",
        "wall_slide_forearms",
        "Glisse murale avant-bras",
        0,
        [],
        "Avant-bras au mur, amplitude courte.",
        "Cotes calmes.",
        15,
        35,
        null,
        "wall_slide_controlled",
      ),
      variant(
        "wall_slide",
        "wall_slide_controlled",
        "Glisse murale controlee",
        1,
        [],
        "Monte un peu plus haut sans compenser.",
        "Nuque longue.",
        20,
        45,
        "wall_slide_forearms",
        "wall_slide_hold",
      ),
      variant(
        "wall_slide",
        "wall_slide_hold",
        "Glisse murale avec pause",
        2,
        [],
        "Ajoute une courte pause dans la zone confortable.",
        "Epaules basses.",
        20,
        45,
        "wall_slide_controlled",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une glisse murale des bras.",
  }),
  exercise({
    id: "prone_swimmer",
    name: "Nageur au sol",
    movementPattern: "pull",
    capabilityDimension: "upper_pull",
    shortDescription: "Renforcer le haut du dos avec un mouvement lent et court.",
    primaryCue: "Deplace les bras comme dans l'eau, sans creuser le bas du dos.",
    teachingSteps: [
      "Allonge-toi sur le ventre.",
      "Deplace lentement les bras devant puis sur les cotes.",
      "Reviens sans chercher une grande amplitude.",
    ],
    commonMistakes: ["Lever trop haut", "Retenir le souffle"],
    breathing: "Respiration libre.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders", "back"],
    difficulty: 1,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "prone_swimmer",
        "prone_swimmer_half",
        "Demi-nageur au sol",
        1,
        [],
        "Fais seulement la moitie du trajet des bras.",
        "Dos calme.",
        10,
        30,
        null,
        "prone_swimmer_controlled",
      ),
      variant(
        "prone_swimmer",
        "prone_swimmer_controlled",
        "Nageur au sol controle",
        2,
        [],
        "Trajet complet mais lent, sans douleur.",
        "Epaules basses.",
        15,
        40,
        "prone_swimmer_half",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un nageur au sol.",
  }),
  exercise({
    id: "ankle_mobility",
    name: "Mobilite des chevilles",
    movementPattern: "mobility",
    capabilityDimension: "mobility",
    shortDescription: "Preparer les appuis et les squats avec une mobilite douce.",
    primaryCue: "Avance le genou lentement sans decoller le talon.",
    teachingSteps: [
      "Place un pied devant l'autre.",
      "Avance le genou vers l'avant dans une amplitude confortable.",
      "Reviens puis change de cote.",
    ],
    commonMistakes: ["Forcer la cheville", "Decoller le talon"],
    breathing: "Respiration calme.",
    requiredEquipment: [],
    targetZones: ["ankles", "knees"],
    cautionZones: ["ankles", "knees"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "ankle_mobility",
        "ankle_rock_small",
        "Bascule cheville courte",
        0,
        [],
        "Amplitude courte, sans douleur.",
        "Talon au sol.",
        15,
        35,
        null,
        "ankle_rock_controlled",
      ),
      variant(
        "ankle_mobility",
        "ankle_rock_controlled",
        "Bascule cheville controlee",
        1,
        [],
        "Avance un peu plus si le talon reste au sol.",
        "Mouvement lent.",
        20,
        45,
        "ankle_rock_small",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une mobilite des chevilles.",
  }),
  exercise({
    id: "hip_mobility_90_90",
    name: "Mobilite des hanches assise",
    movementPattern: "mobility",
    capabilityDimension: "mobility",
    shortDescription: "Explorer la rotation de hanche sans charge ni vitesse.",
    primaryCue: "Bouge lentement et reste loin de la douleur.",
    teachingSteps: [
      "Assieds-toi au sol avec les genoux plies.",
      "Laisse les genoux basculer doucement d'un cote.",
      "Reviens au centre avant de changer.",
    ],
    commonMistakes: ["Forcer l'amplitude", "S'effondrer dans le dos"],
    breathing: "Expire pendant la bascule.",
    requiredEquipment: [],
    targetZones: ["hips", "back", "knees"],
    cautionZones: ["hips", "back", "knees"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "hip_mobility_90_90",
        "seated_hip_switch_small",
        "Bascule de hanches courte",
        0,
        [],
        "Garde les mains au sol si besoin et bouge peu.",
        "Dos long.",
        15,
        35,
        null,
        "ninety_ninety_switch",
      ),
      variant(
        "hip_mobility_90_90",
        "ninety_ninety_switch",
        "Changement 90-90 controle",
        1,
        [],
        "Bascule les deux genoux avec controle.",
        "Respire.",
        20,
        45,
        "seated_hip_switch_small",
        "ninety_ninety_lift",
      ),
      variant(
        "hip_mobility_90_90",
        "ninety_ninety_lift",
        "90-90 avec redressement",
        2,
        [],
        "Redresse un peu le buste dans la position confortable.",
        "Pas de forcing.",
        20,
        45,
        "ninety_ninety_switch",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une mobilite des hanches assise.",
  }),
  exercise({
    id: "thoracic_rotation",
    name: "Rotation douce du haut du dos",
    movementPattern: "mobility",
    capabilityDimension: "mobility",
    shortDescription: "Mobiliser le haut du dos sans chercher une amplitude maximale.",
    primaryCue: "Tourne depuis le haut du dos, pas depuis les lombaires.",
    teachingSteps: [
      "Installe-toi a quatre pattes ou sur le cote.",
      "Ouvre lentement un bras vers le plafond.",
      "Reviens au centre avant de changer.",
    ],
    commonMistakes: ["Forcer la rotation", "Retenir le souffle"],
    breathing: "Expire pendant l'ouverture.",
    requiredEquipment: [],
    targetZones: ["back", "shoulders"],
    cautionZones: ["back", "shoulders", "wrists"],
    difficulty: 0,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "thoracic_rotation",
        "thoracic_rotation_quadruped_short",
        "Rotation quatre pattes courte",
        0,
        [],
        "Ouvre peu le bras, bassin stable.",
        "Amplitude facile.",
        15,
        35,
        null,
        "thoracic_rotation_open_book",
      ),
      variant(
        "thoracic_rotation",
        "thoracic_rotation_open_book",
        "Ouverture livre au sol",
        1,
        [],
        "Sur le cote, ouvre le bras dans une amplitude confortable.",
        "Respire.",
        20,
        45,
        "thoracic_rotation_quadruped_short",
        "thoracic_rotation_reach",
      ),
      variant(
        "thoracic_rotation",
        "thoracic_rotation_reach",
        "Rotation avec allongement",
        2,
        [],
        "Ajoute un allongement du bras avant l'ouverture.",
        "Mouvement fluide.",
        20,
        45,
        "thoracic_rotation_open_book",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'une rotation douce du haut du dos.",
  }),
  exercise({
    id: "single_leg_balance",
    name: "Equilibre sur une jambe",
    movementPattern: "locomotion",
    capabilityDimension: "mobility",
    shortDescription: "Construire un appui stable sans impact.",
    primaryCue: "Cherche une tenue calme, pose le pied des que l'appui se degrade.",
    teachingSteps: [
      "Tiens-toi debout, regard devant.",
      "Allege un pied puis souleve-le si possible.",
      "Repose avant de changer de cote.",
    ],
    commonMistakes: ["Se crisper", "Attendre la perte d'equilibre"],
    breathing: "Respiration calme.",
    requiredEquipment: [],
    targetZones: ["ankles", "knees", "hips"],
    cautionZones: ["ankles", "knees", "hips"],
    difficulty: 0,
    effortSecondsMin: 10,
    effortSecondsMax: 40,
    variants: [
      variant(
        "single_leg_balance",
        "balance_foot_light",
        "Pied allege",
        0,
        [],
        "Garde les deux pieds au sol et allege un appui.",
        "Posture droite.",
        10,
        30,
        null,
        "balance_single_leg_short",
      ),
      variant(
        "single_leg_balance",
        "balance_single_leg_short",
        "Equilibre une jambe court",
        1,
        [],
        "Souleve un pied sur une tenue courte.",
        "Regard fixe.",
        10,
        35,
        "balance_foot_light",
        "balance_single_leg_reach",
      ),
      variant(
        "single_leg_balance",
        "balance_single_leg_reach",
        "Equilibre avec bras qui bougent",
        2,
        [],
        "Bouge lentement les bras sans perdre l'appui.",
        "Pied calme.",
        15,
        40,
        "balance_single_leg_short",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un equilibre sur une jambe.",
  }),
  exercise({
    id: "low_impact_jacks",
    name: "Pas lateraux dynamiques",
    movementPattern: "locomotion",
    capabilityDimension: "cardio_endurance",
    shortDescription: "Faire monter doucement le rythme sans saut.",
    primaryCue: "Reste capable de parler et garde des appuis silencieux.",
    teachingSteps: [
      "Pars debout, pieds sous les hanches.",
      "Ouvre un pied sur le cote puis ramene-le.",
      "Ajoute les bras seulement si le souffle reste calme.",
    ],
    commonMistakes: ["Sauter", "Aller trop vite trop tot"],
    breathing: "Respiration reguliere, sans apnee.",
    requiredEquipment: [],
    targetZones: ["hips", "ankles", "knees"],
    cautionZones: ["ankles", "knees", "hips"],
    difficulty: 0,
    effortSecondsMin: 20,
    effortSecondsMax: 60,
    variants: [
      variant(
        "low_impact_jacks",
        "side_tap_slow",
        "Pas lateral lent",
        0,
        [],
        "Un pas sur le cote, retour au centre, rythme facile.",
        "Appuis silencieux.",
        20,
        45,
        null,
        "step_jack_controlled",
      ),
      variant(
        "low_impact_jacks",
        "step_jack_controlled",
        "Step jack sans saut",
        1,
        [],
        "Ajoute les bras en gardant un pied au sol.",
        "Souffle controle.",
        25,
        60,
        "side_tap_slow",
        "cross_step_jack",
      ),
      variant(
        "low_impact_jacks",
        "cross_step_jack",
        "Pas croises dynamiques",
        2,
        [],
        "Croise legerement derriere puis reviens au centre.",
        "Rythme stable.",
        25,
        60,
        "step_jack_controlled",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder de pas lateraux dynamiques.",
  }),
  exercise({
    id: "shadow_boxing_low",
    name: "Poussees dans l'air",
    movementPattern: "locomotion",
    capabilityDimension: "cardio_endurance",
    shortDescription: "Conditionnement doux du haut du corps sans impact.",
    primaryCue: "Pousse dans l'air sans verrouiller les coudes ni crisper la nuque.",
    teachingSteps: [
      "Tiens-toi debout, genoux souples.",
      "Pousse un bras devant toi puis ramene-le.",
      "Alterne les bras a un rythme confortable.",
    ],
    commonMistakes: ["Frapper fort", "Monter les epaules"],
    breathing: "Expire doucement sur chaque poussee.",
    requiredEquipment: [],
    targetZones: ["shoulders", "back", "hips"],
    cautionZones: ["shoulders", "back", "hips"],
    difficulty: 0,
    effortSecondsMin: 20,
    effortSecondsMax: 60,
    variants: [
      variant(
        "shadow_boxing_low",
        "shadow_push_slow",
        "Poussees lentes dans l'air",
        0,
        [],
        "Pousse lentement un bras apres l'autre.",
        "Nuque detendue.",
        20,
        45,
        null,
        "shadow_push_rhythm",
      ),
      variant(
        "shadow_boxing_low",
        "shadow_push_rhythm",
        "Poussees rythmees dans l'air",
        1,
        [],
        "Garde un rythme regulier sans bloquer les coudes.",
        "Respiration facile.",
        25,
        60,
        "shadow_push_slow",
        "shadow_push_step",
      ),
      variant(
        "shadow_boxing_low",
        "shadow_push_step",
        "Poussees avec pas sur place",
        2,
        [],
        "Ajoute une marche douce sur place.",
        "Reste capable de parler.",
        25,
        60,
        "shadow_push_rhythm",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder de poussees dans l'air.",
  }),
  exercise({
    id: "band_row",
    name: "Tirage avec elastique",
    movementPattern: "pull",
    capabilityDimension: "upper_pull",
    shortDescription: "Ajouter un tirage quand le materiel le permet.",
    primaryCue: "Tire les coudes vers l'arriere sans hausser les epaules.",
    teachingSteps: [
      "Fixe ou tiens l'elastique de facon sure.",
      "Grandis-toi avant de tirer.",
      "Reviens lentement bras tendus.",
    ],
    commonMistakes: ["Tirer avec la nuque", "Relacher d'un coup"],
    breathing: "Expire en tirant.",
    requiredEquipment: ["resistance_band"],
    targetZones: ["shoulders", "back"],
    cautionZones: ["shoulders", "back"],
    difficulty: 1,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "band_row",
        "band_row_light",
        "Tirage elastique leger",
        1,
        ["resistance_band"],
        "Tension legere, retour controle.",
        "Epaules basses.",
        15,
        40,
        null,
        "band_row_standard",
      ),
      variant(
        "band_row",
        "band_row_standard",
        "Tirage elastique",
        2,
        ["resistance_band"],
        "Tension moderee, pas d'a-coup.",
        "Coudes vers l'arriere.",
        20,
        45,
        "band_row_light",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un tirage avec elastique.",
  }),
  exercise({
    id: "farmer_carry",
    name: "Port de charges leger",
    movementPattern: "locomotion",
    capabilityDimension: "posterior_chain",
    shortDescription: "Marcher avec des charges legeres et controlees.",
    primaryCue: "Reste grand, marche lentement et pose les charges si besoin.",
    teachingSteps: [
      "Prends deux charges faciles a controler.",
      "Tiens-toi droit.",
      "Marche lentement puis repose les charges avec controle.",
    ],
    commonMistakes: ["Choisir trop lourd", "Se pencher d'un cote"],
    breathing: "Respiration continue.",
    requiredEquipment: ["dumbbells"],
    targetZones: ["back", "shoulders", "hips"],
    cautionZones: ["back", "shoulders", "wrists"],
    difficulty: 2,
    effortSecondsMin: 15,
    effortSecondsMax: 45,
    variants: [
      variant(
        "farmer_carry",
        "farmer_carry_light",
        "Port de charges leger",
        2,
        ["dumbbells"],
        "Charges faciles, distance courte.",
        "Posture grande.",
        15,
        40,
        null,
        "farmer_carry_standard",
      ),
      variant(
        "farmer_carry",
        "farmer_carry_standard",
        "Port de charges controle",
        3,
        ["dumbbells"],
        "Charges moderees, marche stable.",
        "Pose avant fatigue.",
        20,
        45,
        "farmer_carry_light",
        null,
      ),
    ],
    mediaAlt: "Illustration placeholder d'un port de charges leger.",
  }),
];

export function getExerciseById(exerciseId: string): Exercise | null {
  return STRENGTH_EXERCISES.find((exerciseItem) => exerciseItem.id === exerciseId) ?? null;
}

export function getVariantById(variantId: string): ExerciseVariant | null {
  for (const exerciseItem of STRENGTH_EXERCISES) {
    const found = exerciseItem.variants.find((item) => item.id === variantId);
    if (found) {
      return found;
    }
  }

  return null;
}
