import type { Recipe, RecipeCategory } from "@/features/recipes/recipeTypes";

export const recipeCategoryLabels: Record<RecipeCategory, string> = {
  breakfast: "Petit déjeuner",
  lunch: "Déjeuner",
  dinner: "Dîner",
  snack: "Grignotage",
};

export const recipeCatalog: Recipe[] = [
  {
    id: "catalog-salade-pates-tomates",
    category: "lunch",
    cookMinutes: 10,
    createdAt: "2026-07-20T08:00:00.000Z",
    description: "Une base froide facile à préparer, pensée pour un repas simple à relire dans le carnet.",
    ingredients: [
      { id: "ingredient-1", text: "Pâtes cuites" },
      { id: "ingredient-2", text: "Tomates" },
      { id: "ingredient-3", text: "Concombre" },
      { id: "ingredient-4", text: "Thon ou oeufs" },
      { id: "ingredient-5", text: "Huile d’olive et herbes" },
    ],
    origin: "catalog",
    prepMinutes: 15,
    servings: 2,
    steps: [
      { id: "step-1", text: "Couper les légumes et les mélanger aux pâtes froides." },
      { id: "step-2", text: "Ajouter le thon ou les oeufs." },
      { id: "step-3", text: "Assaisonner simplement, puis garder au frais si besoin." },
    ],
    tags: ["Repas froid", "Préparable"],
    title: "Salade de pâtes et tomates",
    updatedAt: "2026-07-20T08:00:00.000Z",
  },
  {
    id: "catalog-wrap-oeuf-crudites",
    category: "lunch",
    cookMinutes: 8,
    createdAt: "2026-07-20T08:00:00.000Z",
    description: "Un wrap court, pratique, avec un contenu explicite pour éviter les repas trop flous.",
    ingredients: [
      { id: "ingredient-1", text: "Galette de blé" },
      { id: "ingredient-2", text: "Oeufs" },
      { id: "ingredient-3", text: "Salade" },
      { id: "ingredient-4", text: "Carotte râpée" },
      { id: "ingredient-5", text: "Sauce yaourt ou moutarde douce" },
    ],
    origin: "catalog",
    prepMinutes: 10,
    servings: 1,
    steps: [
      { id: "step-1", text: "Cuire les oeufs puis les couper." },
      { id: "step-2", text: "Garnir la galette avec les crudités et les oeufs." },
      { id: "step-3", text: "Rouler serré et couper en deux." },
    ],
    tags: ["Rapide", "À emporter"],
    title: "Wrap oeuf et crudités",
    updatedAt: "2026-07-20T08:00:00.000Z",
  },
  {
    id: "catalog-bol-yaourt-fruits",
    category: "breakfast",
    cookMinutes: 0,
    createdAt: "2026-07-20T08:00:00.000Z",
    description: "Un bol de petit déjeuner très lisible, sans préparation compliquée.",
    ingredients: [
      { id: "ingredient-1", text: "Yaourt nature" },
      { id: "ingredient-2", text: "Fruit de saison" },
      { id: "ingredient-3", text: "Flocons d’avoine" },
      { id: "ingredient-4", text: "Quelques noix ou graines" },
    ],
    origin: "catalog",
    prepMinutes: 5,
    servings: 1,
    steps: [
      { id: "step-1", text: "Verser le yaourt dans un bol." },
      { id: "step-2", text: "Ajouter le fruit coupé, les flocons et les noix." },
    ],
    tags: ["Simple", "Sans cuisson"],
    title: "Bol yaourt, fruit et avoine",
    updatedAt: "2026-07-20T08:00:00.000Z",
  },
  {
    id: "catalog-poelee-legumes-riz",
    category: "dinner",
    cookMinutes: 18,
    createdAt: "2026-07-20T08:00:00.000Z",
    description: "Une assiette chaude facile à adapter avec les légumes disponibles.",
    ingredients: [
      { id: "ingredient-1", text: "Riz cuit" },
      { id: "ingredient-2", text: "Courgette" },
      { id: "ingredient-3", text: "Champignons" },
      { id: "ingredient-4", text: "Pois chiches" },
      { id: "ingredient-5", text: "Épices douces" },
    ],
    origin: "catalog",
    prepMinutes: 10,
    servings: 2,
    steps: [
      { id: "step-1", text: "Faire revenir les légumes coupés." },
      { id: "step-2", text: "Ajouter les pois chiches et les épices." },
      { id: "step-3", text: "Servir avec le riz chaud." },
    ],
    tags: ["Chaud", "Adaptable"],
    title: "Poêlée légumes, riz et pois chiches",
    updatedAt: "2026-07-20T08:00:00.000Z",
  },
  {
    id: "catalog-tartine-fromage-fruit",
    category: "snack",
    cookMinutes: 0,
    createdAt: "2026-07-20T08:00:00.000Z",
    description: "Une option de grignotage posée, avec peu d’éléments à noter.",
    ingredients: [
      { id: "ingredient-1", text: "Pain complet ou aux céréales" },
      { id: "ingredient-2", text: "Fromage frais" },
      { id: "ingredient-3", text: "Fruit" },
    ],
    origin: "catalog",
    prepMinutes: 5,
    servings: 1,
    steps: [
      { id: "step-1", text: "Tartiner le pain." },
      { id: "step-2", text: "Servir avec le fruit à côté." },
    ],
    tags: ["Court", "Sans cuisson"],
    title: "Tartine fromage frais et fruit",
    updatedAt: "2026-07-20T08:00:00.000Z",
  },
];
