import type {
  AdminAction,
  AdminAiFixture,
  AdminAuditFixture,
  AdminContentFixture,
  AdminFixtureNotice,
  AdminMetric,
  AdminModuleUsage,
  AdminOperationFixture,
  AdminRecipeReportFixture,
  AdminRoleFixture,
  AdminStatusItem,
  AdminSubscriptionFixture,
  AdminUserFixture,
} from "./types";

export const adminFixtureNotice: AdminFixtureNotice = {
  title: "Maquette produit - données fictives locales",
  description:
    "Aucune donnée réelle, aucun branchement Supabase, aucune clé privilégiée et aucune mutation ne sont utilisés dans cette interface.",
  generatedAt: "2026-07-16T09:00:00+02:00",
};

const requiredAuditContract = {
  actorRequired: true,
  targetRequired: true,
  reasonRequired: true,
  correlationIdRequired: true,
} as const;

export const adminActionCatalog: AdminAction[] = [
  {
    id: "open-user",
    label: "Ouvrir la fiche",
    mode: "disabled",
    reason: "Lot UI seulement: aucune fiche utilisateur réelle n'est chargée.",
    requiredPermission: "users.read_stub",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "manual-entitlement",
    label: "Accorder un droit",
    mode: "disabled",
    reason: "Lot UI seulement: aucune mutation d'abonnement n'est branchée.",
    requiredPermission: "subscriptions.read_stub",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "publish-content",
    label: "Publier",
    mode: "disabled",
    reason: "Lot UI seulement: aucun contenu réel n'est modifié.",
    requiredPermission: "recipes.publish",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "review-report",
    label: "Traiter le signalement",
    mode: "disabled",
    reason:
      "Lot UI seulement: aucun signalement de recette publique n'est modifié.",
    requiredPermission: "recipes.moderate",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "run-synthetic-analysis",
    label: "Tester sur données synthétiques",
    mode: "simulation",
    reason: "Contrôle visuel sans exécution de modèle ni écriture d'audit.",
    requiredPermission: "analysis.synthetic_run",
    sensitivity: "routine",
    auditContract: requiredAuditContract,
  },
  {
    id: "toggle-rollout",
    label: "Modifier le déploiement",
    mode: "disabled",
    reason: "Lot UI seulement: aucun prompt, règle ou drapeau n'est modifié.",
    requiredPermission: "analysis.rollout",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "retry-job",
    label: "Relancer",
    mode: "disabled",
    reason: "Lot UI seulement: aucune file technique réelle n'est appelée.",
    requiredPermission: "operations.retry",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "inspect-audit-context",
    label: "Voir le contexte",
    mode: "disabled",
    reason: "Lot UI seulement: aucun journal d'audit réel n'est consulté.",
    requiredPermission: "audit.read",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
  {
    id: "export-view",
    label: "Exporter la vue",
    mode: "disabled",
    reason: "Lot UI seulement: aucun export réel n'est généré.",
    requiredPermission: "exports.simulate",
    sensitivity: "sensitive",
    auditContract: requiredAuditContract,
  },
];

export const adminRoleFixtures: AdminRoleFixture[] = [
  {
    id: "ROLE-DEMO-READ",
    label: "Lecture fictive",
    scope: "Consultation des vues agrégées et des catalogues de démonstration.",
    permissions: [
      "overview.read",
      "recipes.read",
      "sport.read",
      "operations.read",
    ],
  },
  {
    id: "ROLE-DEMO-SUPPORT",
    label: "Support fictif",
    scope: "Lecture minimale d'états techniques de comptes de démonstration.",
    permissions: ["overview.read", "users.read_stub", "audit.read"],
  },
  {
    id: "ROLE-DEMO-RECIPE-REVIEW",
    label: "Revue recettes fictive",
    scope: "Consultation et revue simulée des seules recettes publiques.",
    permissions: ["recipes.read", "recipes.moderate", "audit.read"],
  },
];

export const overviewMetrics: AdminMetric[] = [
  {
    id: "registered-users",
    label: "Utilisateurs inscrits",
    value: "12 480",
    detail: "+184 sur 7 jours",
    tone: "success",
    sensitivity: "aggregate",
  },
  {
    id: "active-users",
    label: "Actifs 7 jours",
    value: "4 920",
    detail: "39,4% des comptes fictifs",
    tone: "info",
    sensitivity: "aggregate",
  },
  {
    id: "new-users",
    label: "Nouveaux inscrits",
    value: "318",
    detail: "Maquette de cohorte hebdo",
    tone: "neutral",
    sensitivity: "aggregate",
  },
  {
    id: "known-incidents",
    label: "Incidents connus",
    value: "2",
    detail: "Sans contenu utilisateur",
    tone: "warning",
    sensitivity: "technical",
  },
];

export const moduleUsage: AdminModuleUsage[] = [
  {
    id: "today",
    module: "Aujourd'hui",
    activeUsers: "4 410",
    weeklyChange: "+6,2%",
    adoption: 88,
    tone: "success",
  },
  {
    id: "meal",
    module: "Repas",
    activeUsers: "3 120",
    weeklyChange: "+3,4%",
    adoption: 63,
    tone: "info",
  },
  {
    id: "sport",
    module: "Sport",
    activeUsers: "1 840",
    weeklyChange: "+11,0%",
    adoption: 37,
    tone: "success",
  },
  {
    id: "recipes",
    module: "Recettes",
    activeUsers: "1 260",
    weeklyChange: "+4,7%",
    adoption: 25,
    tone: "info",
  },
  {
    id: "tracking",
    module: "Poids et tabac",
    activeUsers: "980",
    weeklyChange: "-1,8%",
    adoption: 20,
    tone: "warning",
  },
];

export const serviceStates: AdminStatusItem[] = [
  {
    id: "web",
    label: "Application web",
    value: "Opérationnelle",
    detail: "Version fictive admin-ui.1",
    tone: "success",
    sensitivity: "technical",
  },
  {
    id: "sync",
    label: "Synchronisation",
    value: "Dégradée",
    detail: "2 files avec erreurs redigées",
    tone: "warning",
    sensitivity: "technical",
  },
  {
    id: "payments",
    label: "Paiements",
    value: "Lecture seule",
    detail: "Connecteur non branché dans cette passe",
    tone: "neutral",
    sensitivity: "technical",
  },
  {
    id: "audit",
    label: "Audit admin",
    value: "Schéma à venir",
    detail: "Page maquette avec exemples locaux",
    tone: "info",
    sensitivity: "audit_metadata",
  },
];

export const supportUsers: AdminUserFixture[] = [
  {
    id: "USR-DEMO-1042",
    displayName: "Compte pilote A",
    contact: "demo-1042@haru.invalid",
    accountState: "Actif",
    onboarding: "Terminé",
    subscription: "Sport + Recettes",
    lastActivity: "Aujourd'hui 09:20",
    syncState: "Stable",
    tone: "success",
  },
  {
    id: "USR-DEMO-2048",
    displayName: "Compte pilote B",
    contact: "demo-2048@haru.invalid",
    accountState: "Actif",
    onboarding: "À reprendre",
    subscription: "Gratuit",
    lastActivity: "Hier 18:04",
    syncState: "Retard mineur",
    tone: "warning",
  },
  {
    id: "USR-DEMO-3096",
    displayName: "Compte pilote C",
    contact: "demo-3096@haru.invalid",
    accountState: "Accès restreint test",
    onboarding: "Terminé",
    subscription: "Recettes",
    lastActivity: "Il y a 6 jours",
    syncState: "Bloqué test",
    tone: "danger",
  },
  {
    id: "USR-DEMO-4120",
    displayName: "Compte pilote D",
    contact: "demo-4120@haru.invalid",
    accountState: "Actif",
    onboarding: "Terminé",
    subscription: "Sport",
    lastActivity: "Il y a 2 jours",
    syncState: "Stable",
    tone: "info",
  },
];

export const subscriptionRows: AdminSubscriptionFixture[] = [
  {
    id: "SUB-DEMO-001",
    account: "USR-DEMO-1042",
    offer: "Offre combinée",
    source: "Paiement fictif",
    renewal: "2026-08-02",
    appRights: "Sport, Recettes",
    reconciliation: "Aligné",
    tone: "success",
  },
  {
    id: "SUB-DEMO-002",
    account: "USR-DEMO-2048",
    offer: "Gratuit",
    source: "Aucun paiement",
    renewal: "N/A",
    appRights: "Gratuit",
    reconciliation: "Aligné",
    tone: "neutral",
  },
  {
    id: "SUB-DEMO-003",
    account: "USR-DEMO-3096",
    offer: "Recettes",
    source: "Paiement fictif",
    renewal: "2026-07-19",
    appRights: "Droit expiré test",
    reconciliation: "À contrôler",
    tone: "warning",
  },
  {
    id: "SUB-DEMO-004",
    account: "USR-DEMO-4120",
    offer: "Sport",
    source: "Droit manuel fictif",
    renewal: "2026-07-30",
    appRights: "Sport temporaire",
    reconciliation: "Justification manquante test",
    tone: "danger",
  },
];

export const recipeRows: AdminContentFixture[] = [
  {
    id: "REC-DEMO-018",
    title: "Bol complet pois chiches et herbes",
    owner: "Équipe contenu",
    status: "Brouillon",
    category: "Végétarien",
    updatedAt: "2026-07-15",
    reviewState: "Nutrition à relire",
    tone: "warning",
  },
  {
    id: "REC-DEMO-024",
    title: "Soupe froide concombre citron",
    owner: "Équipe contenu",
    status: "Prêt à publier",
    category: "Rapide",
    updatedAt: "2026-07-14",
    reviewState: "Allergènes validés",
    tone: "success",
  },
  {
    id: "REC-DEMO-031",
    title: "Omelette légère aux champignons",
    owner: "Proposition publique fictive",
    status: "En revue",
    category: "Protéiné",
    updatedAt: "2026-07-13",
    reviewState: "Source à vérifier",
    tone: "info",
  },
];

export const sportRows: AdminContentFixture[] = [
  {
    id: "SPT-DEMO-101",
    title: "Squat assisté chaise",
    owner: "Bibliothèque Sport",
    status: "Publié",
    category: "Bas du corps",
    updatedAt: "2026-07-10",
    reviewState: "Précautions validées",
    tone: "success",
  },
  {
    id: "SPT-DEMO-116",
    title: "Pompes inclinées",
    owner: "Bibliothèque Sport",
    status: "Brouillon",
    category: "Haut du corps",
    updatedAt: "2026-07-12",
    reviewState: "Vidéo manquante",
    tone: "warning",
  },
  {
    id: "SPT-DEMO-122",
    title: "Respiration de récupération",
    owner: "Programme mobilité",
    status: "Publié",
    category: "Récupération",
    updatedAt: "2026-07-11",
    reviewState: "Adapté débutant",
    tone: "info",
  },
];

export const recipeReportRows: AdminRecipeReportFixture[] = [
  {
    id: "MOD-DEMO-009",
    reportType: "Droits d'utilisation",
    recipeId: "REC-PUBLIC-DEMO-884",
    recipeTitle: "Salade croquante aux agrumes",
    priority: "Haute",
    queueAge: "2 h",
    reviewState: "À examiner",
    tone: "danger",
  },
  {
    id: "MOD-DEMO-014",
    reportType: "Allergène à vérifier",
    recipeId: "REC-PUBLIC-DEMO-441",
    recipeTitle: "Granola maison aux noix",
    priority: "Normale",
    queueAge: "1 j",
    reviewState: "Relecture attendue",
    tone: "warning",
  },
  {
    id: "MOD-DEMO-022",
    reportType: "Contenu hors sujet",
    recipeId: "REC-PUBLIC-DEMO-118",
    recipeTitle: "Fiche recette incomplète",
    priority: "Basse",
    queueAge: "3 j",
    reviewState: "À qualifier",
    tone: "info",
  },
];

export const aiRows: AdminAiFixture[] = [
  {
    id: "AI-DEMO-001",
    capability: "Analyse déterministe repas",
    version: "rules-demo.7",
    rollout: "100% maquette",
    lastSyntheticRun: "2026-07-15 16:00",
    guardrailState: "Données synthétiques uniquement",
    tone: "success",
  },
  {
    id: "AI-DEMO-002",
    capability: "Conseils Sport",
    version: "prompt-demo.3",
    rollout: "Pilote visuel",
    lastSyntheticRun: "2026-07-14 11:30",
    guardrailState: "Contre-indications à relire",
    tone: "warning",
  },
  {
    id: "AI-DEMO-003",
    capability: "Aide support",
    version: "disabled",
    rollout: "0%",
    lastSyntheticRun: "Jamais",
    guardrailState: "Non activé",
    tone: "neutral",
  },
];

export const operationRows: AdminOperationFixture[] = [
  {
    id: "OPS-DEMO-001",
    service: "Queue synchronisation",
    state: "Retard",
    lastCheck: "09:01",
    queue: "18 jobs fictifs",
    detail: "Payloads masqués dans la maquette",
    tone: "warning",
  },
  {
    id: "OPS-DEMO-002",
    service: "Export de compte",
    state: "Disponible",
    lastCheck: "08:58",
    queue: "0 job",
    detail: "Action non branchée",
    tone: "success",
  },
  {
    id: "OPS-DEMO-003",
    service: "Demandes liées au compte",
    state: "Lecture seule",
    lastCheck: "08:55",
    queue: "2 demandes fictives",
    detail: "Aucune opération de compte dans ce lot",
    tone: "neutral",
  },
  {
    id: "OPS-DEMO-004",
    service: "Migrations",
    state: "Non vérifié",
    lastCheck: "N/A",
    queue: "Lecture locale",
    detail: "Aucune migration créée dans cette passe",
    tone: "info",
  },
];

export const auditRows: AdminAuditFixture[] = [
  {
    id: "AUD-DEMO-1001",
    actor: "super-admin-demo@haru.invalid",
    actorRole: "ROLE-DEMO-READ",
    action: "admin.fixture.view",
    requiredPermission: "overview.read",
    targetType: "admin_mock",
    targetId: "ADMIN-DEMO",
    targetLabel: "Back-office maquette",
    reason: "Parcours produit",
    correlationId: "CORR-DEMO-20260716-001",
    createdAt: "2026-07-16 09:00",
    metadata: "Exemple local sans trace réelle",
    tone: "info",
  },
  {
    id: "AUD-DEMO-1002",
    actor: "content-demo@haru.invalid",
    actorRole: "ROLE-DEMO-RECIPE-REVIEW",
    action: "recipe.preview",
    requiredPermission: "recipes.read",
    targetType: "public_recipe",
    targetId: "REC-DEMO-024",
    targetLabel: "Soupe froide concombre citron",
    reason: "Relecture éditoriale fictive",
    correlationId: "CORR-DEMO-20260715-002",
    createdAt: "2026-07-15 14:15",
    metadata: "Aucune publication réelle",
    tone: "success",
  },
  {
    id: "AUD-DEMO-1003",
    actor: "support-demo@haru.invalid",
    actorRole: "ROLE-DEMO-SUPPORT",
    action: "account.read_stub",
    requiredPermission: "users.read_stub",
    targetType: "account_stub",
    targetId: "USR-DEMO-2048",
    targetLabel: "Compte pilote B",
    reason: "Simulation de support",
    correlationId: "CORR-DEMO-20260715-003",
    createdAt: "2026-07-15 10:42",
    metadata: "État technique uniquement",
    tone: "warning",
  },
];

export const sensitiveDataExcluded = [
  "repas personnels",
  "poids",
  "tabac",
  "réponses comportementales",
  "tokens",
  "secrets",
  "données bancaires",
];
